apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana
  description: Deployment of Grafana for KubeCon Demo
  # Example for optional annotations
  annotations:
    github.com/project-slug: backstage-kubecon-demo/grafana
    backstage.io/kubernetes-id: grafana
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
